apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: guestbook
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          - name: MONGODB_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: guestbook-mongodb-credentials
                key: connection-string
          - name: MONGODB_DATABASE
            value: snake_game
          - name: ADMIN_USERNAME
            valueFrom:
              secretKeyRef:
                name: guestbook-admin-credentials
                key: username
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: guestbook-admin-credentials
                key: password
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: guestbook/api/messages
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: guestbook/api/messages
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
          volumeMounts:
            - name: dataprotection-keys
              mountPath: /root/.aspnet/DataProtection-Keys
      volumes:
        - name: dataprotection-keys
          persistentVolumeClaim:
            claimName: guestbook-datakeys-pvc