apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: guestbook
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
          name: http
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: MONGODB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongodb.connectionStringSecret }}
              key: mongodb-root-username
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongodb.connectionStringSecret }}
              key: mongodb-root-password
        - name: MONGODB_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongodb.connectionStringSecret }}
              key: mongodb-database
        - name: MONGODB_CONNECTION_STRING
          value: "mongodb://$(MONGODB_ROOT_USERNAME):$(MONGODB_ROOT_PASSWORD)@mongodb-service:27017/$(MONGODB_DATABASE)?authSource=admin"
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        livenessProbe:
          httpGet:
            path: /api/messages
            port: {{ .Values.service.port }}
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/messages
            port: {{ .Values.service.port }}
          initialDelaySeconds: 5
          periodSeconds: 10