# Template for admin credentials
# Copy to admin-secret.yaml and fill in your values
# DO NOT commit the actual secret file

apiVersion: v1
kind: Secret
metadata:
  name: guestbook-admin-credentials-example
  namespace: default
type: Opaque
stringData:
  username: "YOUR_ADMIN_USERNAME"
  password: "YOUR_ADMIN_PASSWORD"