apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-healthcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-healthcheck
  template:
    metadata:
      labels:
        app: nginx-healthcheck
    spec:
      containers:
      - name: nginx
        image: ghcr.io/mymh13/kube-snake/healthcheck:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-healthcheck-service
spec:
  selector:
    app: nginx-healthcheck
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP