replicaCount: 2

image:
  repository: ghcr.io/mymh13/kube-snake/snake-api
  tag: "main-809402a-20251016213451"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi