replicaCount: 1  # Keep at 1 until Redis is deployed

image:
  repository: ghcr.io/mymh13/kube-snake/snake-api
  tag: "main-9d62acb-20251017084204"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

env:
  - name: REDIS_CONNECTION
    value: "redis-master.kube-snake.svc.cluster.local:6379"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi