apiVersion: v1
kind: Secret
metadata:
  name: guestbook-admin-credentials
  namespace: default
type: Opaque
data:
  # This is an example file, the real file is gitignored and has encoded username/pass
  username: <base64-encoded-username>
  password: <base64-encoded-password>