replicaCount: 2

image:
  repository: ghcr.io/mymh13/kube-snake/snake
  tag: "main-c1a753d-20251016214146"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 32Mi