replicaCount: 2

image:
  repository: ghcr.io/mymh13/kube-snake/snake
  tag: "main-ebb66e0-20251016214758"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 32Mi