replicaCount: 2

image:
  repository: ghcr.io/mymh13/kube-snake/snake
  tag: "main-707b81d-20251017094439"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 32Mi