replicaCount: 1

image:
  repository: ghcr.io/mymh13/kube-snake/snake
  tag: "main-9042659-20251017071852"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 32Mi